// Centralized interaction configurations
// Shared slide lists for common room interactions

const SLIDES_VISIBLE_COMMON = [
  "slide20",
  "slide21",
  "slide22",
  "slide29",
  "slide30",
  "slide31",
  "slide32",
  "slide33",
  "slide34",
  "slide35",
  "slide36",
  "slide41",
  "slide99",
];
const SLIDES_HOVER_ONLY_COMMON = [
  "slide21",
  "slide22",
  "slide29",
  "slide30",
  "slide31",
  "slide32",
  "slide33",
  "slide34",
  "slide35",
  "slide36",
  "slide41",
  "slide99",
];
const SLIDES_HIGHLIGHT_ONLY_COMMON = SLIDES_VISIBLE_COMMON;
export const INTERACTION_CONFIGS = [
  {
    id: "picture",
    manager: "fg",
    config: {
      id: "picture",
      layers: {
        default: "picture-1",
        active: "picture-2",
        hover: "picture-hover",
      },
      activeSlide: "slide7",
      visibleSlides: ["slide4", "slide5", "slide6", "slide7"],
      hover: true,
      hoverWhenInactive: false,
      click: true,
      clickWhenInactive: false,
      bboxLayer: "default",
      eventsPrefix: "picture",
      highlightMode: "active",
      highlightParallax: true,
    },
  },
  {
    id: "book-floor",
    manager: "fg",
    config: {
      id: "book-floor",
      layers: {
        default: "book-floor",
        hover: "book-floor-hover",
      },
      visibleSlides: SLIDES_VISIBLE_COMMON,
      hover: true,
      hoverWhenInactive: true,
      hoverOnlyOnSlides: SLIDES_HOVER_ONLY_COMMON,
      click: true,
      clickWhenInactive: true,
      bboxLayer: "hover",
      eventsPrefix: "book-floor",
      highlightOnlyOnSlides: SLIDES_HIGHLIGHT_ONLY_COMMON,
      highlightMode: "visible",
      highlightParallax: true,
      highlightOffset: { x: 0, y: 8 },
    },
  },
  {
    id: "box",
    manager: "fg",
    config: {
      id: "box",
      layers: {
        default: "box",
        hover: "box-hover",
      },
      visibleSlides: SLIDES_VISIBLE_COMMON,
      hover: true,
      hoverWhenInactive: true,
      hoverOnlyOnSlides: SLIDES_HOVER_ONLY_COMMON,
      click: true,
      clickWhenInactive: true,
      bboxLayer: "hover",
      eventsPrefix: "box",
      highlightOnlyOnSlides: SLIDES_HIGHLIGHT_ONLY_COMMON,
      highlightMode: "visible",
      highlightParallax: true,
      highlightOffset: { x: 0, y: 8 },
    },
  },
  {
    id: "football-0",
    manager: "fg",
    config: {
      id: "football-0",
      layers: {
        default: "football-0",
        hover: "football-hover",
      },
      visibleSlides: SLIDES_VISIBLE_COMMON,
      hover: true,
      hoverWhenInactive: true,
      hoverOnlyOnSlides: SLIDES_HOVER_ONLY_COMMON,
      click: true,
      clickWhenInactive: true,
      bboxLayer: "hover",
      eventsPrefix: "football",
      highlightOnlyOnSlides: SLIDES_HIGHLIGHT_ONLY_COMMON,
      highlightMode: "visible",
      highlightParallax: true,
      highlightOffset: { x: 0, y: 8 },
    },
  },
  {
    id: "wheel-pump",
    manager: "fg",
    config: {
      id: "wheel-pump",
      layers: { active: "wheel-pump-spot", hover: "wheel-pump-hover" },
      visibleSlides: ["slide43"],
      hover: true,
      hoverWhenInactive: true,
      hoverOnlyOnSlides: ["slide43"],
      click: true,
      clickWhenInactive: true,
      bboxLayer: "hover",
      eventsPrefix: "wheel-pump",
      highlightOnlyOnSlides: ["slide43"],
      highlightMode: "visible",
      highlightParallax: true,
    },
  },
];
